name: Maven Release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  maven_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Maven Release
        uses: qcastel/github-actions-maven-release@master
        env:
          JAVA_HOME: /usr/lib/jvm/java-21-openjdk/
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          maven-args: "-Dmaven.javadoc.skip=true -DskipTests"
          git-release-bot-name: github-actions[bot]
          git-release-bot-email: github-actions[bot]@users.noreply.github.com
          version-minor: true
          maven-development-version-number: ${parsedVersion.majorVersion}.${parsedVersion.nextMinorVersion}-SNAPSHOT
          maven-release-version-number: ${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.0
          maven-servers: '[{"id": "github", "username": "${{ github.actor }}", "password": "${{ secrets.DEPLOY_TOKEN }}" }]'
